### PR TITLE
fix: propagate cancelation signal using task store

### LINKED ISSUE #245: [Bug] Do not try to move task to failed state on ErrConcurrentModification
If execution fails because of concurrent modification (eg. concurrent cancellation), event processor should not try to move the task to failed state as this will always fail.

### PR DESCRIPTION
**Pull request by yarolegovich**
fixes #245

### CODE REVIEW

File: e2e/cancellation_test.go [hunk 1]
```diff
@@ -0,0 +1,123 @@
+// Copyright 2025 The A2A Authors
```
Comment (nahapetyan-serob) [inline e2e/cancellation_test.go]: should this be 2026?
